### ISSUE TITLE
noSuchThingAsCheats

### ISSUE THREAD

**Issue by Jymit** [Jymit/CheatSheet#6]
```
main:
  name: 'moshi-moshi'
  whitelist:
    - 'SSIDNameHere'
  plugins:
    grid:
      enabled: true
      report: true
      exclude:
        - 'SSIDNameHere'

ui:
    display:
      enabled: true
      type: 'waveshare_2'
      color: 'black'
```
